// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/fulfillment-service/internal/idp (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=client_mock.go -package=idp . Client
//

// Package idp is a generated GoMock package.
package idp

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AssignClientRolesToUser mocks base method.
func (m *MockClient) AssignClientRolesToUser(ctx context.Context, organizationName, userID, clientID string, roles []*Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignClientRolesToUser", ctx, organizationName, userID, clientID, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignClientRolesToUser indicates an expected call of AssignClientRolesToUser.
func (mr *MockClientMockRecorder) AssignClientRolesToUser(ctx, organizationName, userID, clientID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignClientRolesToUser", reflect.TypeOf((*MockClient)(nil).AssignClientRolesToUser), ctx, organizationName, userID, clientID, roles)
}

// AssignIdpManagerPermissions mocks base method.
func (m *MockClient) AssignIdpManagerPermissions(ctx context.Context, organizationName, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignIdpManagerPermissions", ctx, organizationName, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignIdpManagerPermissions indicates an expected call of AssignIdpManagerPermissions.
func (mr *MockClientMockRecorder) AssignIdpManagerPermissions(ctx, organizationName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignIdpManagerPermissions", reflect.TypeOf((*MockClient)(nil).AssignIdpManagerPermissions), ctx, organizationName, userID)
}

// AssignOrganizationAdminPermissions mocks base method.
func (m *MockClient) AssignOrganizationAdminPermissions(ctx context.Context, organizationName, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignOrganizationAdminPermissions", ctx, organizationName, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignOrganizationAdminPermissions indicates an expected call of AssignOrganizationAdminPermissions.
func (mr *MockClientMockRecorder) AssignOrganizationAdminPermissions(ctx, organizationName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignOrganizationAdminPermissions", reflect.TypeOf((*MockClient)(nil).AssignOrganizationAdminPermissions), ctx, organizationName, userID)
}

// AssignOrganizationRolesToUser mocks base method.
func (m *MockClient) AssignOrganizationRolesToUser(ctx context.Context, organizationName, userID string, roles []*Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignOrganizationRolesToUser", ctx, organizationName, userID, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignOrganizationRolesToUser indicates an expected call of AssignOrganizationRolesToUser.
func (mr *MockClientMockRecorder) AssignOrganizationRolesToUser(ctx, organizationName, userID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignOrganizationRolesToUser", reflect.TypeOf((*MockClient)(nil).AssignOrganizationRolesToUser), ctx, organizationName, userID, roles)
}

// CreateOrganization mocks base method.
func (m *MockClient) CreateOrganization(ctx context.Context, org *Organization) (*Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, org)
	ret0, _ := ret[0].(*Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockClientMockRecorder) CreateOrganization(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockClient)(nil).CreateOrganization), ctx, org)
}

// CreateUser mocks base method.
func (m *MockClient) CreateUser(ctx context.Context, organizationName string, user *User) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, organizationName, user)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockClientMockRecorder) CreateUser(ctx, organizationName, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockClient)(nil).CreateUser), ctx, organizationName, user)
}

// DeleteOrganization mocks base method.
func (m *MockClient) DeleteOrganization(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganization", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganization indicates an expected call of DeleteOrganization.
func (mr *MockClientMockRecorder) DeleteOrganization(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganization", reflect.TypeOf((*MockClient)(nil).DeleteOrganization), ctx, name)
}

// DeleteUser mocks base method.
func (m *MockClient) DeleteUser(ctx context.Context, organizationName, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, organizationName, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockClientMockRecorder) DeleteUser(ctx, organizationName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockClient)(nil).DeleteUser), ctx, organizationName, userID)
}

// GetOrganization mocks base method.
func (m *MockClient) GetOrganization(ctx context.Context, name string) (*Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganization", ctx, name)
	ret0, _ := ret[0].(*Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganization indicates an expected call of GetOrganization.
func (mr *MockClientMockRecorder) GetOrganization(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganization", reflect.TypeOf((*MockClient)(nil).GetOrganization), ctx, name)
}

// GetUser mocks base method.
func (m *MockClient) GetUser(ctx context.Context, organizationName, userID string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, organizationName, userID)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockClientMockRecorder) GetUser(ctx, organizationName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockClient)(nil).GetUser), ctx, organizationName, userID)
}

// GetUserClientRoles mocks base method.
func (m *MockClient) GetUserClientRoles(ctx context.Context, organizationName, userID, clientID string) ([]*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserClientRoles", ctx, organizationName, userID, clientID)
	ret0, _ := ret[0].([]*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserClientRoles indicates an expected call of GetUserClientRoles.
func (mr *MockClientMockRecorder) GetUserClientRoles(ctx, organizationName, userID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserClientRoles", reflect.TypeOf((*MockClient)(nil).GetUserClientRoles), ctx, organizationName, userID, clientID)
}

// GetUserOrganizationRoles mocks base method.
func (m *MockClient) GetUserOrganizationRoles(ctx context.Context, organizationName, userID string) ([]*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrganizationRoles", ctx, organizationName, userID)
	ret0, _ := ret[0].([]*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrganizationRoles indicates an expected call of GetUserOrganizationRoles.
func (mr *MockClientMockRecorder) GetUserOrganizationRoles(ctx, organizationName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrganizationRoles", reflect.TypeOf((*MockClient)(nil).GetUserOrganizationRoles), ctx, organizationName, userID)
}

// ListClientRoles mocks base method.
func (m *MockClient) ListClientRoles(ctx context.Context, organizationName, clientID string) ([]*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClientRoles", ctx, organizationName, clientID)
	ret0, _ := ret[0].([]*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClientRoles indicates an expected call of ListClientRoles.
func (mr *MockClientMockRecorder) ListClientRoles(ctx, organizationName, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClientRoles", reflect.TypeOf((*MockClient)(nil).ListClientRoles), ctx, organizationName, clientID)
}

// ListOrganizationRoles mocks base method.
func (m *MockClient) ListOrganizationRoles(ctx context.Context, organizationName string) ([]*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizationRoles", ctx, organizationName)
	ret0, _ := ret[0].([]*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizationRoles indicates an expected call of ListOrganizationRoles.
func (mr *MockClientMockRecorder) ListOrganizationRoles(ctx, organizationName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationRoles", reflect.TypeOf((*MockClient)(nil).ListOrganizationRoles), ctx, organizationName)
}

// ListUsers mocks base method.
func (m *MockClient) ListUsers(ctx context.Context, organizationName string) ([]*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, organizationName)
	ret0, _ := ret[0].([]*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockClientMockRecorder) ListUsers(ctx, organizationName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockClient)(nil).ListUsers), ctx, organizationName)
}

// RemoveClientRolesFromUser mocks base method.
func (m *MockClient) RemoveClientRolesFromUser(ctx context.Context, organizationName, userID, clientID string, roles []*Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveClientRolesFromUser", ctx, organizationName, userID, clientID, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveClientRolesFromUser indicates an expected call of RemoveClientRolesFromUser.
func (mr *MockClientMockRecorder) RemoveClientRolesFromUser(ctx, organizationName, userID, clientID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveClientRolesFromUser", reflect.TypeOf((*MockClient)(nil).RemoveClientRolesFromUser), ctx, organizationName, userID, clientID, roles)
}

// RemoveOrganizationRolesFromUser mocks base method.
func (m *MockClient) RemoveOrganizationRolesFromUser(ctx context.Context, organizationName, userID string, roles []*Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOrganizationRolesFromUser", ctx, organizationName, userID, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveOrganizationRolesFromUser indicates an expected call of RemoveOrganizationRolesFromUser.
func (mr *MockClientMockRecorder) RemoveOrganizationRolesFromUser(ctx, organizationName, userID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOrganizationRolesFromUser", reflect.TypeOf((*MockClient)(nil).RemoveOrganizationRolesFromUser), ctx, organizationName, userID, roles)
}
