#
# Copyright (c) 2025 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#

# This indicates if the chart is being deployed to an OpenShift or Kind cluster. Valid values are `openshift` and `kind`.
variant: kind

# This indicates if the debug mode is enabled. This will run the services under the control of the 'dlv' debugger
# and is intended only for development environments.
debug: false

# Certificate configuration:
certs:

  # This defines the cert-manager issuer that will be used for the certificates used by the service. The default is to
  # use a cluster wide issuer, but there is no default value for the name, so it must be set.
  issuerRef:
    kind: ClusterIssuer
    name:

  # This defines the trusted CA certificates bundle. It must be the name of a configmap in the release namespace
  # that contains trusted CA certificates in PEM format.
  caBundle:
    configMap:

# This defines the hostname used to access the public API from outside the cluster. The default is to use the hostname
# of the Kubernetes service. For example, if the application is deployed in a namespace named 'osac' then the default
# hostname will be 'fulfillment-api.osac.svc.cluster.local'.
externalHostname:

# This defines the hostname used to access both the public and private APIs from outside the cluster. It is typically
# accessible only from the administrator's internal network. The default is to use the hostname of the Kubernetes
# service. For example, if the application is deployed in a namespace named 'osac' then the default hostname will be
# 'fulfillment-internal-api.osac.svc.cluster.local'.
#
# The administrator is responsible for ensuring that this hostname is accessible only from the internal network and not
# accessible to regular users. This isn't strictly required because access is subject to authentication and
# authorization, but it is good practice to restrict network-level access as an additional layer of defense.
internalHostname:

# Authentication and authorization configuration:
auth:

  # This defines the URL of the OAuth issuer used for authentication. This parameter is mandatory.
  issuerUrl:

# Logging configuration:
log:

  # This defines the log level for all components. Valid values are 'debug', 'info', 'warn', and 'error'.
  #
  # Note that setting this to 'debug' will significantly increase the size of logs and may impact service performance.
  level: info

  # This controls whether HTTP/gRPC headers are logged.
  #
  # Note that setting this to 'true' may result in sensitive information being logged, avoid doing this in production
  # environments.
  headers: false

  # This controls whether HTTP/gRPC request and response bodies are logged.
  #
  # Note that setting this to 'true' may result in sensitive information being logged, avoid doing this in production
  # environments.
  bodies: false

# Image configuration:
images:
  service: ghcr.io/osac/fulfillment-service:main
  envoy: docker.io/envoyproxy/envoy:v1.37.1

# Database connection configuration. The service expects an external PostgreSQL database to be available. The database
# should be created before installing this chart.
database:

  # List of sources for database connection parameters. Each entry maps keys from a ConfigMap or Secret to named
  # database connection parameters. Each item has a 'key' field that indicates the name of the key in the ConfigMap (or
  # Secret) and a 'param' field indicating the name of the connection parameter.
  #
  # In addition to typical PostgreSQL connection parameters the chart also supports the following:
  #
  # - `url`      - The complete PostgreSQL connection URL.
  # - `host`     - The host name or IP address of the database server.
  # - `port`     - The port number of the database server.
  # - `user`     - The PostgreSQL user name.
  # - `password` - The PostgreSQL password.
  # - `dbname`   - The PostgreSQL database name.
  #
  # For example, if the database URL is stored in a ConfigMap names `db-config` in a key named `uri` and the user name
  # and password are stored in a Secret named `db-secret` in keys named `user` and `password`, the connection
  # configuration would look like this:
  #
  #   connection:
  #   - configMap:
  #       name: db-config
  #       items:
  #       - key: uri
  #         param: url
  #   - secret:
  #       name: db-secret
  #       items:
  #       - key: user
  #         param: user
  #       - key: password
  #         param: password
  #
  # The keys of the ConfigMap and secret don't need to match the parameter names. In the above example the URL is in a
  # `uri` key but the connection parameter name is `url`.
  connection: []
