{{/*
Copyright (c) 2025 Red Hat Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
*/}}

{{ if eq .Values.variant "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: {{ .Release.Namespace }}
  name: fulfillment-api
spec:
  host: {{ .Values.externalHostname }}
  to:
    kind: Service
    name: fulfillment-api
  port:
    targetPort: external-api
  tls:
    termination: passthrough

{{ if .Values.internalHostname }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: {{ .Release.Namespace }}
  name: fulfillment-internal-api
spec:
  host: {{ .Values.internalHostname }}
  to:
    kind: Service
    name: fulfillment-internal-api
  port:
    targetPort: internal-api
  tls:
    termination: passthrough
{{ end }}

{{ end }}

{{ if eq .Values.variant "kind" }}
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: TLSRoute
metadata:
  namespace: {{ .Release.Namespace }}
  name: fulfillment-api
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: envoy-gateway
    name: default
    sectionName: tls
  hostnames:
  - {{ include "fulfillment-api.hostname" . }}
  rules:
  - backendRefs:
    - name: fulfillment-api
      port: 8000

{{ if .Values.internalHostname }}
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: TLSRoute
metadata:
  namespace: {{ .Release.Namespace }}
  name: fulfillment-internal-api
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: envoy-gateway
    name: default
    sectionName: tls
  hostnames:
  - {{ include "fulfillment-internal-api.hostname" . }}
  rules:
  - backendRefs:
    - name: fulfillment-internal-api
      port: 8001
{{ end }}

{{ end }}
