//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/public/v1/host_types_service.proto

//go:build protoopaque

package publicv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostTypesListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Offset      int32                  `protobuf:"varint,1,opt,name=offset,proto3,oneof"`
	xxx_hidden_Limit       int32                  `protobuf:"varint,2,opt,name=limit,proto3,oneof"`
	xxx_hidden_Filter      *string                `protobuf:"bytes,3,opt,name=filter,proto3,oneof"`
	xxx_hidden_Order       *string                `protobuf:"bytes,4,opt,name=order,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HostTypesListRequest) Reset() {
	*x = HostTypesListRequest{}
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostTypesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostTypesListRequest) ProtoMessage() {}

func (x *HostTypesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HostTypesListRequest) GetOffset() int32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *HostTypesListRequest) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *HostTypesListRequest) GetFilter() string {
	if x != nil {
		if x.xxx_hidden_Filter != nil {
			return *x.xxx_hidden_Filter
		}
		return ""
	}
	return ""
}

func (x *HostTypesListRequest) GetOrder() string {
	if x != nil {
		if x.xxx_hidden_Order != nil {
			return *x.xxx_hidden_Order
		}
		return ""
	}
	return ""
}

func (x *HostTypesListRequest) SetOffset(v int32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *HostTypesListRequest) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *HostTypesListRequest) SetFilter(v string) {
	x.xxx_hidden_Filter = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *HostTypesListRequest) SetOrder(v string) {
	x.xxx_hidden_Order = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *HostTypesListRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HostTypesListRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *HostTypesListRequest) HasFilter() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *HostTypesListRequest) HasOrder() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *HostTypesListRequest) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Offset = 0
}

func (x *HostTypesListRequest) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

func (x *HostTypesListRequest) ClearFilter() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Filter = nil
}

func (x *HostTypesListRequest) ClearOrder() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Order = nil
}

type HostTypesListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Index of the first result. If not specified the default value will be zero.
	Offset *int32
	// Maximum number of results to be returned by the server. When not specified all the results will be returned. Note
	// that there may not be enough results to return, and that the server may decide, for performance reasons, to return
	// less results than requested.
	Limit *int32
	// Filter criteria.
	//
	// The value of this parameter is a [CEL](https://cel.dev) expression used to select which objects to return. The
	// built-in `this` variable refers to the object being tested and `now` refers to the current date and time. If the
	// expression evaluates to `true` the object is included in the results. For example, to retrieve all host types
	// with names starting with `gpu`:
	//
	//	this.metadata.name.startsWith("gpu")
	//
	// If this isn't provided, or if the value is empty, then all the host types that the user has permission to see
	// will be returned. Not all CEL constructs are currently supported for implementation reasons; see the filter
	// documentation (docs/FILTER.md) for the full details.
	Filter *string
	// Order criteria.
	//
	// The syntax of this parameter is similar to the syntax of the _order by_ clause of a SQL statement, but using the
	// names of the attributes of the host type instead of the names of the columns of a table. For example, in order to
	// sort the templates descending by title the value should be:
	//
	//	name desc
	//
	// If the parameter isn't provided, or if the value is empty, then the order of the results is undefined.
	Order *string
}

func (b0 HostTypesListRequest_builder) Build() *HostTypesListRequest {
	m0 := &HostTypesListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Offset = *b.Offset
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Limit = *b.Limit
	}
	if b.Filter != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Filter = b.Filter
	}
	if b.Order != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Order = b.Order
	}
	return m0
}

type HostTypesListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Size  int32                  `protobuf:"varint,1,opt,name=size,proto3"`
	xxx_hidden_Total int32                  `protobuf:"varint,2,opt,name=total,proto3"`
	xxx_hidden_Items *[]*HostType           `protobuf:"bytes,3,rep,name=items,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HostTypesListResponse) Reset() {
	*x = HostTypesListResponse{}
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostTypesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostTypesListResponse) ProtoMessage() {}

func (x *HostTypesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HostTypesListResponse) GetSize() int32 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *HostTypesListResponse) GetTotal() int32 {
	if x != nil {
		return x.xxx_hidden_Total
	}
	return 0
}

func (x *HostTypesListResponse) GetItems() []*HostType {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *HostTypesListResponse) SetSize(v int32) {
	x.xxx_hidden_Size = v
}

func (x *HostTypesListResponse) SetTotal(v int32) {
	x.xxx_hidden_Total = v
}

func (x *HostTypesListResponse) SetItems(v []*HostType) {
	x.xxx_hidden_Items = &v
}

type HostTypesListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Actual number of items returned. Note that this may be smaller than the value requested in the `limit` parameter
	// of the request if there are not enough items, or of the system decides that returning that number of items isn't
	// feasible or convenient for performance reasons.
	Size int32
	// Total number of items of the collection that match the search criteria, regardless of the number of results
	// requested with the `limit` parameter.
	Total int32
	// List of results.
	Items []*HostType
}

func (b0 HostTypesListResponse_builder) Build() *HostTypesListResponse {
	m0 := &HostTypesListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Size = b.Size
	x.xxx_hidden_Total = b.Total
	x.xxx_hidden_Items = &b.Items
	return m0
}

type HostTypesGetRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostTypesGetRequest) Reset() {
	*x = HostTypesGetRequest{}
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostTypesGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostTypesGetRequest) ProtoMessage() {}

func (x *HostTypesGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HostTypesGetRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *HostTypesGetRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

type HostTypesGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 HostTypesGetRequest_builder) Build() *HostTypesGetRequest {
	m0 := &HostTypesGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type HostTypesGetResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Object *HostType              `protobuf:"bytes,1,opt,name=object,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostTypesGetResponse) Reset() {
	*x = HostTypesGetResponse{}
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostTypesGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostTypesGetResponse) ProtoMessage() {}

func (x *HostTypesGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HostTypesGetResponse) GetObject() *HostType {
	if x != nil {
		return x.xxx_hidden_Object
	}
	return nil
}

func (x *HostTypesGetResponse) SetObject(v *HostType) {
	x.xxx_hidden_Object = v
}

func (x *HostTypesGetResponse) HasObject() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Object != nil
}

func (x *HostTypesGetResponse) ClearObject() {
	x.xxx_hidden_Object = nil
}

type HostTypesGetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Object *HostType
}

func (b0 HostTypesGetResponse_builder) Build() *HostTypesGetResponse {
	m0 := &HostTypesGetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Object = b.Object
	return m0
}

type HostTypesCreateRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Object *HostType              `protobuf:"bytes,1,opt,name=object,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostTypesCreateRequest) Reset() {
	*x = HostTypesCreateRequest{}
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostTypesCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostTypesCreateRequest) ProtoMessage() {}

func (x *HostTypesCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HostTypesCreateRequest) GetObject() *HostType {
	if x != nil {
		return x.xxx_hidden_Object
	}
	return nil
}

func (x *HostTypesCreateRequest) SetObject(v *HostType) {
	x.xxx_hidden_Object = v
}

func (x *HostTypesCreateRequest) HasObject() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Object != nil
}

func (x *HostTypesCreateRequest) ClearObject() {
	x.xxx_hidden_Object = nil
}

type HostTypesCreateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Object *HostType
}

func (b0 HostTypesCreateRequest_builder) Build() *HostTypesCreateRequest {
	m0 := &HostTypesCreateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Object = b.Object
	return m0
}

type HostTypesCreateResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Object *HostType              `protobuf:"bytes,1,opt,name=object,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostTypesCreateResponse) Reset() {
	*x = HostTypesCreateResponse{}
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostTypesCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostTypesCreateResponse) ProtoMessage() {}

func (x *HostTypesCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HostTypesCreateResponse) GetObject() *HostType {
	if x != nil {
		return x.xxx_hidden_Object
	}
	return nil
}

func (x *HostTypesCreateResponse) SetObject(v *HostType) {
	x.xxx_hidden_Object = v
}

func (x *HostTypesCreateResponse) HasObject() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Object != nil
}

func (x *HostTypesCreateResponse) ClearObject() {
	x.xxx_hidden_Object = nil
}

type HostTypesCreateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Object *HostType
}

func (b0 HostTypesCreateResponse_builder) Build() *HostTypesCreateResponse {
	m0 := &HostTypesCreateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Object = b.Object
	return m0
}

type HostTypesUpdateRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Object     *HostType              `protobuf:"bytes,1,opt,name=object,proto3"`
	xxx_hidden_UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3"`
	xxx_hidden_Lock       bool                   `protobuf:"varint,3,opt,name=lock,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HostTypesUpdateRequest) Reset() {
	*x = HostTypesUpdateRequest{}
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostTypesUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostTypesUpdateRequest) ProtoMessage() {}

func (x *HostTypesUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HostTypesUpdateRequest) GetObject() *HostType {
	if x != nil {
		return x.xxx_hidden_Object
	}
	return nil
}

func (x *HostTypesUpdateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.xxx_hidden_UpdateMask
	}
	return nil
}

func (x *HostTypesUpdateRequest) GetLock() bool {
	if x != nil {
		return x.xxx_hidden_Lock
	}
	return false
}

func (x *HostTypesUpdateRequest) SetObject(v *HostType) {
	x.xxx_hidden_Object = v
}

func (x *HostTypesUpdateRequest) SetUpdateMask(v *fieldmaskpb.FieldMask) {
	x.xxx_hidden_UpdateMask = v
}

func (x *HostTypesUpdateRequest) SetLock(v bool) {
	x.xxx_hidden_Lock = v
}

func (x *HostTypesUpdateRequest) HasObject() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Object != nil
}

func (x *HostTypesUpdateRequest) HasUpdateMask() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdateMask != nil
}

func (x *HostTypesUpdateRequest) ClearObject() {
	x.xxx_hidden_Object = nil
}

func (x *HostTypesUpdateRequest) ClearUpdateMask() {
	x.xxx_hidden_UpdateMask = nil
}

type HostTypesUpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Object     *HostType
	UpdateMask *fieldmaskpb.FieldMask
	// Lock enables optimistic locking. When set to true, the server verifies that the current version of the object
	// matches the value of the metadata.version field of the submitted object. If they differ the update will be
	// rejected. This is useful to prevent lost updates when multiple clients are modifying the same object concurrently.
	Lock bool
}

func (b0 HostTypesUpdateRequest_builder) Build() *HostTypesUpdateRequest {
	m0 := &HostTypesUpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Object = b.Object
	x.xxx_hidden_UpdateMask = b.UpdateMask
	x.xxx_hidden_Lock = b.Lock
	return m0
}

type HostTypesUpdateResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Object *HostType              `protobuf:"bytes,1,opt,name=object,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostTypesUpdateResponse) Reset() {
	*x = HostTypesUpdateResponse{}
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostTypesUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostTypesUpdateResponse) ProtoMessage() {}

func (x *HostTypesUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HostTypesUpdateResponse) GetObject() *HostType {
	if x != nil {
		return x.xxx_hidden_Object
	}
	return nil
}

func (x *HostTypesUpdateResponse) SetObject(v *HostType) {
	x.xxx_hidden_Object = v
}

func (x *HostTypesUpdateResponse) HasObject() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Object != nil
}

func (x *HostTypesUpdateResponse) ClearObject() {
	x.xxx_hidden_Object = nil
}

type HostTypesUpdateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Object *HostType
}

func (b0 HostTypesUpdateResponse_builder) Build() *HostTypesUpdateResponse {
	m0 := &HostTypesUpdateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Object = b.Object
	return m0
}

type HostTypesDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostTypesDeleteRequest) Reset() {
	*x = HostTypesDeleteRequest{}
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostTypesDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostTypesDeleteRequest) ProtoMessage() {}

func (x *HostTypesDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HostTypesDeleteRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *HostTypesDeleteRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

type HostTypesDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 HostTypesDeleteRequest_builder) Build() *HostTypesDeleteRequest {
	m0 := &HostTypesDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type HostTypesDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostTypesDeleteResponse) Reset() {
	*x = HostTypesDeleteResponse{}
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostTypesDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostTypesDeleteResponse) ProtoMessage() {}

func (x *HostTypesDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_host_types_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type HostTypesDeleteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 HostTypesDeleteResponse_builder) Build() *HostTypesDeleteResponse {
	m0 := &HostTypesDeleteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_osac_public_v1_host_types_service_proto protoreflect.FileDescriptor

var file_osac_public_v1_host_types_service_proto_rawDesc = string([]byte{
	0x0a, 0x27, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6d,
	0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x6f, 0x73, 0x61, 0x63, 0x2f,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0,
	0x01, 0x0a, 0x14, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12,
	0x1b, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x02, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x22, 0x71, 0x0a, 0x15, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2e, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x25, 0x0a, 0x13, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x48, 0x0a, 0x14, 0x48,
	0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x4a, 0x0a, 0x16, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x30, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x22, 0x4b, 0x0a, 0x17, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f,
	0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x9b,
	0x01, 0x0a, 0x16, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x52, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x63, 0x6b,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x4b, 0x0a, 0x17,
	0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x28, 0x0a, 0x16, 0x48, 0x6f, 0x73,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xcd,
	0x05, 0x0a, 0x09, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x7b, 0x0a, 0x04,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6f, 0x73, 0x61,
	0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x26, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x20, 0x12, 0x1e, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x68,
	0x6f, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x85, 0x01, 0x0a, 0x03, 0x47, 0x65,
	0x74, 0x12, 0x23, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x33, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x2d, 0x62, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x23, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76,
	0x31, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x7b, 0x69, 0x64,
	0x7d, 0x12, 0x91, 0x01, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x26, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f,
	0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x36, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x30, 0x3a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x62, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x1e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x75, 0x6c, 0x66,
	0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x9d, 0x01, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x26, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x42, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x3c, 0x3a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x62, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x32, 0x2a, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x68,
	0x6f, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x7b, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x2e, 0x69, 0x64, 0x7d, 0x12, 0x86, 0x01, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x26, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x2b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x25, 0x2a, 0x23, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x68,
	0x6f, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0xd9,
	0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x2e, 0x76, 0x31, 0x42, 0x15, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x50,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d,
	0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x76, 0x31,
	0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0e, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1b, 0x4f, 0x73, 0x61, 0x63,
	0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var file_osac_public_v1_host_types_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_osac_public_v1_host_types_service_proto_goTypes = []any{
	(*HostTypesListRequest)(nil),    // 0: osac.public.v1.HostTypesListRequest
	(*HostTypesListResponse)(nil),   // 1: osac.public.v1.HostTypesListResponse
	(*HostTypesGetRequest)(nil),     // 2: osac.public.v1.HostTypesGetRequest
	(*HostTypesGetResponse)(nil),    // 3: osac.public.v1.HostTypesGetResponse
	(*HostTypesCreateRequest)(nil),  // 4: osac.public.v1.HostTypesCreateRequest
	(*HostTypesCreateResponse)(nil), // 5: osac.public.v1.HostTypesCreateResponse
	(*HostTypesUpdateRequest)(nil),  // 6: osac.public.v1.HostTypesUpdateRequest
	(*HostTypesUpdateResponse)(nil), // 7: osac.public.v1.HostTypesUpdateResponse
	(*HostTypesDeleteRequest)(nil),  // 8: osac.public.v1.HostTypesDeleteRequest
	(*HostTypesDeleteResponse)(nil), // 9: osac.public.v1.HostTypesDeleteResponse
	(*HostType)(nil),                // 10: osac.public.v1.HostType
	(*fieldmaskpb.FieldMask)(nil),   // 11: google.protobuf.FieldMask
}
var file_osac_public_v1_host_types_service_proto_depIdxs = []int32{
	10, // 0: osac.public.v1.HostTypesListResponse.items:type_name -> osac.public.v1.HostType
	10, // 1: osac.public.v1.HostTypesGetResponse.object:type_name -> osac.public.v1.HostType
	10, // 2: osac.public.v1.HostTypesCreateRequest.object:type_name -> osac.public.v1.HostType
	10, // 3: osac.public.v1.HostTypesCreateResponse.object:type_name -> osac.public.v1.HostType
	10, // 4: osac.public.v1.HostTypesUpdateRequest.object:type_name -> osac.public.v1.HostType
	11, // 5: osac.public.v1.HostTypesUpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	10, // 6: osac.public.v1.HostTypesUpdateResponse.object:type_name -> osac.public.v1.HostType
	0,  // 7: osac.public.v1.HostTypes.List:input_type -> osac.public.v1.HostTypesListRequest
	2,  // 8: osac.public.v1.HostTypes.Get:input_type -> osac.public.v1.HostTypesGetRequest
	4,  // 9: osac.public.v1.HostTypes.Create:input_type -> osac.public.v1.HostTypesCreateRequest
	6,  // 10: osac.public.v1.HostTypes.Update:input_type -> osac.public.v1.HostTypesUpdateRequest
	8,  // 11: osac.public.v1.HostTypes.Delete:input_type -> osac.public.v1.HostTypesDeleteRequest
	1,  // 12: osac.public.v1.HostTypes.List:output_type -> osac.public.v1.HostTypesListResponse
	3,  // 13: osac.public.v1.HostTypes.Get:output_type -> osac.public.v1.HostTypesGetResponse
	5,  // 14: osac.public.v1.HostTypes.Create:output_type -> osac.public.v1.HostTypesCreateResponse
	7,  // 15: osac.public.v1.HostTypes.Update:output_type -> osac.public.v1.HostTypesUpdateResponse
	9,  // 16: osac.public.v1.HostTypes.Delete:output_type -> osac.public.v1.HostTypesDeleteResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_osac_public_v1_host_types_service_proto_init() }
func file_osac_public_v1_host_types_service_proto_init() {
	if File_osac_public_v1_host_types_service_proto != nil {
		return
	}
	file_osac_public_v1_host_type_type_proto_init()
	file_osac_public_v1_host_types_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_public_v1_host_types_service_proto_rawDesc), len(file_osac_public_v1_host_types_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_osac_public_v1_host_types_service_proto_goTypes,
		DependencyIndexes: file_osac_public_v1_host_types_service_proto_depIdxs,
		MessageInfos:      file_osac_public_v1_host_types_service_proto_msgTypes,
	}.Build()
	File_osac_public_v1_host_types_service_proto = out.File
	file_osac_public_v1_host_types_service_proto_goTypes = nil
	file_osac_public_v1_host_types_service_proto_depIdxs = nil
}
