#
# Copyright (c) 2025 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

name: Check pull request

on:
  pull_request:
    branches:
    - main

jobs:

  check-pre-commit:
    name: Check pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
    - uses: pre-commit/action@v3.0.1

  check-code-format:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-go
    - run: |
        gofmt -s -l -w .
        git diff --exit-code

  check-generated-code:
    name: Check generated code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: bufbuild/buf-action@v1
      with:
        version: '1.50.0'
        setup_only: true
    - run: |
        buf generate
        git diff --exit-code

  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-go
    - run: |
        ginkgo run -r internal

  build-binaries:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-go
    - uses: goreleaser/goreleaser-action@v7
      with:
        args: build --snapshot --clean

  run-integration-tests-helm:
    name: Run integration tests - Helm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-go
    - run: |
        echo '127.0.0.1 fulfillment-api.osac.svc.cluster.local' | sudo tee -a /etc/hosts
        echo '127.0.0.1 fulfillment-internal-api.osac.svc.cluster.local' | sudo tee -a /etc/hosts
        echo '127.0.0.1 keycloak.keycloak.svc.cluster.local' | sudo tee -a /etc/hosts
        IT_DEPLOY_MODE=helm ginkgo run -v it
    - if: always()
      uses: actions/upload-artifact@v7
      with:
        name: logs-helm
        path: logs
        retention-days: 7

  run-integration-tests-kustomize:
    name: Run integration tests - Kustomize
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-go
    - run: |
        echo '127.0.0.1 fulfillment-api.osac.svc.cluster.local' | sudo tee -a /etc/hosts
        echo '127.0.0.1 fulfillment-internal-api.osac.svc.cluster.local' | sudo tee -a /etc/hosts
        echo '127.0.0.1 keycloak.keycloak.svc.cluster.local' | sudo tee -a /etc/hosts
        IT_DEPLOY_MODE=kustomize ginkgo run -v it
    - if: always()
      uses: actions/upload-artifact@v7
      with:
        name: logs-kustomize
        path: logs
        retention-days: 7
