{{/*
Copyright (c) 2025 Red Hat Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
*/}}

apiVersion: authorino.kuadrant.io/v1beta3
kind: AuthConfig
metadata:
  namespace: {{ .Release.Namespace }}
  name: fulfillment-service
spec:
  hosts:
  - "*"
  authentication:
    "fulfillment-api":
      kubernetesTokenReview:
        audiences:
        # TODO: This is the default audience for the Kubernetes API server. We should probably create a custom audience,
        # for example `fulfillment-api`, but then the users will need to create tokens for that audience. For example:
        #
        # $ kubectl create token -n osac --audience=fulfillment-api client
        #
        # It is not clear to me if we can also use that audience for the tokens generated automatically for the service
        # accounts of other pods, for example for the `controller` pods. It may be possible using a projected service
        # account token, something like this:
        #
        # apiVersion: v1
        # kind: Pod
        # metadata:
        #   name: my
        # spec:
        #   containers:
        #   - volumeMounts:
        #     - mountPath: /var/run/secrets/tokens
        #       name: api-token
        #   volumes:
        #   - name: api-token
        #     projected:
        #       sources:
        #       - serviceAccountToken:
        #           path: api-token
        #           audience: fulfillment-api
        #
        # But that needs to be tested.
        #
        # Note also that different flavours of Kubernetes use different audicences for the service account tokens. Kind
        # uses the full DNS name `kubernetes.default.svc.cluster.local`, but OpenShift uses the `kubernetes.default.svc`
        # abbreviation.
        - https://kubernetes.default.svc
        - https://kubernetes.default.svc.cluster.local
      overrides:
        authnMethod:
          value: serviceaccount
    "keycloak-jwt":
      jwt:
        issuerUrl: {{ required "auth.issuerUrl is required" .Values.auth.issuerUrl }}
      overrides:
        authnMethod:
          value: jwt
  authorization:
    default:
      opa:
        allValues: true
        rego: |
          import rego.v1

          # Define admin service accounts:
          admin_service_accounts := {
            "system:serviceaccount:{{ .Release.Namespace }}:admin",
            "system:serviceaccount:{{ .Release.Namespace }}:controller",
          }

          # Define admin groups:
          admin_groups := {
            "admins",
          }

          # Get the gRPC method:
          grpc_method := input.context.request.http.path

          # Get the subject name:
          subject_name = input.auth.identity.user.username if {
            input.auth.identity.authnMethod == "serviceaccount"
          }
          subject_name = input.auth.identity.username if {
            input.auth.identity.authnMethod == "jwt"
          }

          # Get the subject groups:
          subject_groups = input.auth.identity.user.groups if {
            input.auth.identity.authnMethod == "serviceaccount"
          }
          subject_groups = input.auth.identity.groups if {
            input.auth.identity.authnMethod == "jwt"
          }

          # Check if an account is an admin account:
          default is_admin = false
          is_admin if {
            subject_name in admin_service_accounts
          }
          is_admin if {
            some group in subject_groups
            group in admin_groups
          }

          # Check if an account is a client account:
          default is_client = false
          is_client if {
            not is_admin
          }

          # Allow metadata, reflection and health to everyone:
          allow if {
            startswith(grpc_method, "/metadata.")
          }
          allow if {
            startswith(grpc_method, "/grpc.reflection.")
          }
          allow if {
            startswith(grpc_method, "/grpc.health.")
          }

          # Allow specific methods to clients:
          allow if {
            is_client
            grpc_method in {
              "/osac.public.v1.ClusterTemplates/Get",
              "/osac.public.v1.ClusterTemplates/List",
              "/osac.public.v1.Clusters/Create",
              "/osac.public.v1.Clusters/Delete",
              "/osac.public.v1.Clusters/Get",
              "/osac.public.v1.Clusters/GetKubeconfig",
              "/osac.public.v1.Clusters/GetKubeconfigViaHttp",
              "/osac.public.v1.Clusters/GetPassword",
              "/osac.public.v1.Clusters/GetPasswordViaHttp",
              "/osac.public.v1.Clusters/List",
              "/osac.public.v1.Clusters/Update",
              "/osac.public.v1.ComputeInstanceTemplates/Get",
              "/osac.public.v1.ComputeInstanceTemplates/List",
              "/osac.public.v1.ComputeInstances/Create",
              "/osac.public.v1.ComputeInstances/Delete",
              "/osac.public.v1.ComputeInstances/Get",
              "/osac.public.v1.ComputeInstances/List",
              "/osac.public.v1.ComputeInstances/Update",
              "/osac.public.v1.Events/Watch",
              "/osac.public.v1.HostTypes/Get",
              "/osac.public.v1.HostTypes/List",
              "/osac.public.v1.NetworkClasses/Create",
              "/osac.public.v1.NetworkClasses/Delete",
              "/osac.public.v1.NetworkClasses/Get",
              "/osac.public.v1.NetworkClasses/List",
              "/osac.public.v1.NetworkClasses/Update",
              "/osac.public.v1.Subnets/Create",
              "/osac.public.v1.Subnets/Delete",
              "/osac.public.v1.Subnets/Get",
              "/osac.public.v1.Subnets/List",
              "/osac.public.v1.Subnets/Update",
              "/osac.public.v1.VirtualNetworks/Create",
              "/osac.public.v1.VirtualNetworks/Delete",
              "/osac.public.v1.VirtualNetworks/Get",
              "/osac.public.v1.VirtualNetworks/List",
              "/osac.public.v1.VirtualNetworks/Update",
              "/osac.public.v1.SecurityGroups/Create",
              "/osac.public.v1.SecurityGroups/Delete",
              "/osac.public.v1.SecurityGroups/Get",
              "/osac.public.v1.SecurityGroups/List",
              "/osac.public.v1.SecurityGroups/Update",
              "/osac.public.v1.PublicIPs/Create",
              "/osac.public.v1.PublicIPs/Delete",
              "/osac.public.v1.PublicIPs/Get",
              "/osac.public.v1.PublicIPs/List",
            }
          }

          # Allow everything to admins:
          allow if {
            is_admin
          }
  response:
    success:
      headers:
        "x-subject":
          json:
            properties:
              user:
                expression: |
                  auth.identity.authnMethod == "jwt"
                    ? auth.identity.username
                    : auth.identity.user.username.split(":")[3]
              tenants:
                expression: |
                  auth.authorization.default.is_admin
                    ? ["*"]
                    : auth.identity.authnMethod == "jwt"
                      ? auth.identity.groups
                      : [auth.identity.user.username.split(":")[2]]
